api/urls.py
from django.urls import path

from .views import DispenseView, LoginView, MaterialView, ValidateView

app_name = "api"

urlpatterns = [
    path("start", LoginView.as_view(), name="login"),
    path("material", MaterialView.as_view(), name="material"),
    path("dispense", DispenseView.as_view(), name="dispense"),
    path("validate", ValidateView.as_view(), name="validate"),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django_registration.backends.activation import views as reg_views

import api.urls
import main.urls
from users.forms import UserRegistrationForm

urlpatterns = [
    # api urls
    path(settings.API_URL, include(api.urls)),
    # admin urls
    path(settings.ADMIN_URL, admin.site.urls),
    # django-registration urls
    path(
        "registrace/",
        reg_views.RegistrationView.as_view(form_class=UserRegistrationForm),
        name="django_registration_register",
    ),
    path(
        "registrace/aktivace/dokoncena/",
        TemplateView.as_view(
            template_name="django_registration/activation_complete.html"
        ),
        name="django_registration_activation_complete",
    ),
    path(
        "registrace/aktivace/<str:activation_key>/",
        reg_views.ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "registrace/dokoncena/",
        TemplateView.as_view(
            template_name="django_registration/registration_complete.html"
        ),
        name="django_registration_complete",
    ),
    path(
        "registrace/uzavrena/",
        TemplateView.as_view(
            template_name="django_registration/registration_disallowed.html"
        ),
        name="django_registration_disallowed",
    ),
    # main urls
    path("", include(main.urls)),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

main/urls.py
from django.urls import path

from .views import (
    AboutView,
    DispenseEditView,
    DispenseNewView,
    DispenseView,
    LocationView,
    LoginView,
    LogoutView,
    PasswordResetView,
    RegionListView,
    RegionView,
)

app_name = "main"

urlpatterns = [
    path("", RegionListView.as_view(), name="region_list"),
    path("oblast/<int:id>", RegionView.as_view(), name="region"),
    path("lokalita/<int:id>", LocationView.as_view(), name="location"),
    path("o-aplikaci", AboutView.as_view(), name="about"),
    path("reset-hesla/", PasswordResetView.as_view(), name="password_reset"),
    path("prihlaseni/", LoginView.as_view(), name="login"),
    path("odhlasit/", LogoutView.as_view(), name="logout"),
    path("vydej/", DispenseView.as_view(), name="dispense"),
    path(
        "vydej/novy/<int:id_card_no>/", DispenseNewView.as_view(), name="dispense_new"
    ),
    path("vydej/editace/<int:pk>/", DispenseEditView.as_view(), name="dispense_edit",),
]

config/templates/django_registration/activation_complete.html
{% extends "main/base.html" %}

{% block title %}Registrace{% endblock title %}
{% block content %}

<div class="alert alert-success" role="alert">
  <h2 class="h5">Účet byl aktivován</h2>
  <p class="mb-0">Pokračujte na <a href="{% url "main:login" %}">přihlášení</a>.</p>
</div>

{% endblock content %}

config/templates/django_registration/activation_failed.html
{% extends "main/base.html" %}

{% block title %}Registrace{% endblock title %}
{% block content %}

<div class="alert alert-danger" role="alert">
  <h2 class="h5">Aktivace se nezdařila</h2>
  <p class="mb-0">
    {% if activation_error.code == "already_activated" %}
      Účet již byl aktivován.
    {% elif activation_error.code == "expired" %}
      Aktivační odkaz je již neplatný.
    {% else %}
      Aktivační klíč je neplatný. Zkontrolujte prosím, zda byl celý odkaz správně zkopírován do prohlížeče.
    {% endif %}
  </p>
</div>

{% endblock content %}

config/templates/django_registration/registration_complete.html
{% extends "main/base.html" %}

{% block title %}Registrace{% endblock title %}
{% block content %}

<div class="alert alert-success" role="alert">
  <h2 class="h5">Registrace byla úspěšná</h2>
  <p>Na vaši emailovou adresu dorazí email s odkazem pro potvrzení a aktivaci vašeho uživatelského účtu.</p>
  <p class="mb-0">Po aktivaci se budete moci přihlásit a zažádat koordinátora o přidání do lokality.</p>
</div>


{% endblock content %}

config/templates/django_registration/registration_disallowed.html
{% extends "main/base.html" %}

{% block title %}Registrace{% endblock title %}
{% block content %}

<div class="alert alert-warning" role="alert">
  <h2 class="h5">Registrace jsou pozastaveny</h2>
  <p class="mb-0">Omlouváme se, registrace nových uživatelů momentálně nejsou možné.</p>
</div>

{% endblock content %}

config/templates/django_registration/registration_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Registrace{% endblock title %}
{% block content %}

<h2 class="h5 mt-4 mb-2">Registrace</h2>

{% crispy form %}

{% endblock content %}