api/urls.py
from django.urls import path

from .views import DispenseView, LoginView, MaterialView, ValidateView

app_name = "api"

urlpatterns = [
    path("start", LoginView.as_view(), name="login"),
    path("material", MaterialView.as_view(), name="material"),
    path("dispense", DispenseView.as_view(), name="dispense"),
    path("validate", ValidateView.as_view(), name="validate"),
]

main/urls.py
from django.urls import path

from .views import (
    AboutView,
    DispenseEditView,
    DispenseNewView,
    DispenseView,
    LocationView,
    LoginView,
    LogoutView,
    PasswordResetView,
    RegionListView,
    RegionView,
)

app_name = "main"

urlpatterns = [
    path("", RegionListView.as_view(), name="region_list"),
    path("oblast/<int:id>", RegionView.as_view(), name="region"),
    path("lokalita/<int:id>", LocationView.as_view(), name="location"),
    path("o-aplikaci", AboutView.as_view(), name="about"),
    path("reset-hesla/", PasswordResetView.as_view(), name="password_reset"),
    path("prihlaseni/", LoginView.as_view(), name="login"),
    path("odhlasit/", LogoutView.as_view(), name="logout"),
    path("vydej/", DispenseView.as_view(), name="dispense"),
    path(
        "vydej/novy/<int:id_card_no>/", DispenseNewView.as_view(), name="dispense_new"
    ),
    path("vydej/editace/<int:pk>/", DispenseEditView.as_view(), name="dispense_edit",),
]

main/models.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models

from .utils import setup_user_permissons

help_markdown = "Markdown syntaxe. Nadpisy nejsou povolené a nezobrazí se na webu!"


class Region(models.Model):
    ACTIVE = "active"
    DISABLED = "disabled"
    STATUS_CHOICES = [
        (ACTIVE, "aktivní"),
        (DISABLED, "pozastaveno"),
    ]

    name = models.CharField("název", max_length=1000, unique=True)
    about = models.TextField("popis", null=True, blank=True, help_text=help_markdown)
    status = models.CharField(
        "status", max_length=10, choices=STATUS_CHOICES, default=ACTIVE, db_index=True
    )
    admins = models.ManyToManyField(
        settings.AUTH_USER_MODEL, verbose_name="správce", through="RegionAdmin",
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "Oblast"
        verbose_name_plural = "Oblasti"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.location_set.all().update(region_name=self.name)
        self.material_set.all().update(region_name=self.name)


class RegionAdmin(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="uživatel", on_delete=models.CASCADE
    )
    region = models.ForeignKey(Region, verbose_name="oblast", on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Správce oblasti"
        verbose_name_plural = "Správci oblasti"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        setup_user_permissons(self.user)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        setup_user_permissons(self.user)


class Material(models.Model):
    ACTIVE = "active"
    DISABLED = "disabled"
    STATUS_CHOICES = [
        (ACTIVE, "k dispozici"),
        (DISABLED, "blokován"),
    ]

    name = models.CharField("název", max_length=1000)
    region = models.ForeignKey(Region, verbose_name="oblast", on_delete=models.PROTECT)
    status = models.CharField(
        "status", max_length=10, choices=STATUS_CHOICES, default=ACTIVE, db_index=True
    )
    limit = models.FloatField("limit výdeje", null=True, blank=True)
    period = models.PositiveIntegerField("perioda výdeje", null=True, blank=True)
    # denormalized for fast __str__() without related queries
    region_name = models.CharField("název regionu", max_length=1000)

    class Meta:
        ordering = ["region_name", "name"]
        verbose_name = "Materiál"
        verbose_name_plural = "Materiály"

    def __str__(self):
        return f"{self.region_name} / {self.name}"

    def save(self, *args, **kwargs):
        self.region_name = self.region.name
        super().save(*args, **kwargs)

    @classmethod
    def get_available(cls, location_id):
        return cls.objects.filter(
            materialrecord__location__id=location_id,
            materialrecord__operation=MaterialRecord.RECEIVED,
        ).distinct()


class Location(models.Model):
    ACTIVE = "active"
    DISABLED = "disabled"
    STATUS_CHOICES = [
        (ACTIVE, "aktivní"),
        (DISABLED, "pozastavena"),
    ]

    name = models.CharField("název", max_length=1000)
    region = models.ForeignKey(Region, verbose_name="oblast", on_delete=models.PROTECT)
    status = models.CharField(
        "status", max_length=10, choices=STATUS_CHOICES, default=ACTIVE, db_index=True
    )
    about = models.TextField("popis", null=True, blank=True, help_text=help_markdown)
    address = models.TextField("adresa", null=True, blank=True)
    phone = models.CharField("telefon", max_length=20, null=True, blank=True)
    staff = models.ManyToManyField(
        settings.AUTH_USER_MODEL, verbose_name="personál", through="LocationStaff",
    )
    # denormalized for fast __str__() without related queries
    region_name = models.CharField("název regionu", max_length=1000)

    class Meta:
        ordering = ["id"]
        verbose_name = "Lokalita"
        verbose_name_plural = "Lokality"

    def __str__(self):
        return f"#{self.id} - {self.region_name} / {self.name}"

    def save(self, *args, **kwargs):
        self.region_name = self.region.name
        super().save(*args, **kwargs)


class LocationStaff(models.Model):
    PENDING = "pending"
    ADMIN = "admin"
    VOLUNTEER = "volunteer"
    STATUS_CHOICES = [
        (PENDING, "čekatel"),
        (ADMIN, "koordinátor"),
        (VOLUNTEER, "dobrovolník"),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="uživatel", on_delete=models.CASCADE
    )
    location = models.ForeignKey(
        Location, verbose_name="lokalita", on_delete=models.CASCADE
    )
    status = models.CharField(
        "status", max_length=10, choices=STATUS_CHOICES, default=PENDING
    )

    class Meta:
        ordering = ["location", "user"]
        verbose_name = "Personál lokality"
        verbose_name_plural = "Personál lokality"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        setup_user_permissons(self.user)

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        setup_user_permissons(self.user)

    @classmethod
    def is_assigned(cls, user, location):
        return (
            cls.objects.filter(user=user, location=location)
            .exclude(status=LocationStaff.PENDING)
            .exists()
        )


class Dispensed(models.Model):
    material = models.ForeignKey(
        Material, verbose_name="materiál", on_delete=models.PROTECT
    )
    location = models.ForeignKey(
        Location, verbose_name="lokalita", on_delete=models.PROTECT
    )
    region = models.ForeignKey(Region, verbose_name="oblast", on_delete=models.PROTECT)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="uživatel", on_delete=models.PROTECT
    )
    quantity = models.PositiveIntegerField("množství")
    created = models.DateTimeField("vytvořeno", auto_now_add=True)
    changed = models.DateTimeField("upraveno", auto_now=True)
    id_card_no = models.BigIntegerField("číslo dokladu", db_index=True)

    class Meta:
        ordering = ["-created"]
        verbose_name = "Výdej"
        verbose_name_plural = "Výdeje"

    def clean(self):
        if self.material.region_id != self.location.region_id:
            raise ValidationError("Nesouhlasí oblast materiálu a lokality.")

    def save(self, *args, **kwargs):
        self.region = self.location.region
        super().save(*args, **kwargs)


class MaterialRecord(models.Model):
    RECEIVED = "received"
    RETURNED = "returned"
    DISPENSED = "dispensed"
    OPERATION_CHOICES = [
        (RECEIVED, "přijetí"),
        (RETURNED, "vrácení"),
        (DISPENSED, "výdej"),
    ]

    material = models.ForeignKey(
        Material, verbose_name="materiál", on_delete=models.PROTECT
    )
    location = models.ForeignKey(
        Location, verbose_name="lokalita", on_delete=models.PROTECT
    )
    region = models.ForeignKey(Region, verbose_name="oblast", on_delete=models.PROTECT)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name="uživatel", on_delete=models.PROTECT
    )
    quantity = models.IntegerField("množství")
    date = models.DateTimeField("datum", auto_now_add=True)
    operation = models.CharField(
        "operace", max_length=10, choices=OPERATION_CHOICES, db_index=True
    )

    class Meta:
        ordering = ["-date"]
        verbose_name = "Záznam pohybu materiálu"
        verbose_name_plural = "Záznamy pohybů materiálů"

    def clean(self):
        if self.material.region_id != self.location.region_id:
            raise ValidationError("Nesouhlasí oblast materiálu a lokality.")

    def save(self, *args, **kwargs):
        self.region = self.location.region

        if self.operation == self.RECEIVED:
            self.quantity = abs(self.quantity)
        else:
            self.quantity = -abs(self.quantity)

        super().save(*args, **kwargs)


class Blacklist(models.Model):
    id_card_no = models.BigIntegerField("číslo průkazu", db_index=True)
    reason = models.TextField("zdůvodnění", null=True, blank=True)

main/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from pagedown.widgets import AdminPagedownWidget

from .models import Location


class LoginForm(forms.Form):
    email = forms.CharField(label="Email", max_length=100)
    password = forms.CharField(
        label="Heslo", widget=forms.PasswordInput(), max_length=100
    )
    location = forms.IntegerField(label="Číslo lokality")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-horizontal"
        self.helper.label_class = "col-sm-2"
        self.helper.field_class = "col-sm-4"
        self.helper.add_input(Submit("submit", "Přihlásit"))

    def clean_location(self):
        location_id = self.cleaned_data["location"]
        if not Location.objects.filter(id=location_id).exists():
            raise forms.ValidationError(f"Lokalita číslo {location_id} neexistuje.")
        return location_id


class DispenseStartForm(forms.Form):
    id_card_no = forms.IntegerField(label="Číslo dokladu")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "form-inline mb-4"
        self.helper.field_class = "ml-3"
        self.helper.add_input(Submit("submit", "Ověřit"))


class DispenseItemForm(forms.Form):
    quantity = forms.IntegerField(label="množství", initial=0)

    def __init__(self, material, *args, **kwargs):
        super(DispenseItemForm, self).__init__(
            prefix=f"m{material.id}", *args, **kwargs
        )
        self.material = material


class LocationAdminForm(forms.ModelForm):
    class Meta:
        model = Location
        fields = "__all__"
        widgets = {"about": AdminPagedownWidget()}

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    DetailView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
    View,
)

from .forms import DispenseItemForm, DispenseStartForm, LoginForm
from .models import Dispensed, Location, LocationStaff, Material, Region


class AboutView(TemplateView):
    template_name = "main/about.html"


class PasswordResetView(TemplateView):
    template_name = "main/under_construction.html"


class LoginView(FormView):
    template_name = "main/login.html"
    form_class = LoginForm

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data["email"], password=form.cleaned_data["password"],
        )
        if user is not None:
            login(self.request, user)
            self.request.session["location_id"] = form.cleaned_data["location"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("main:dispense")

    def get_initial(self):
        initial = super().get_initial()
        initial["location"] = self.request.GET.get("location")
        return initial


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect(reverse("main:login"))


class DispenseView(LoginRequiredMixin, FormView):
    template_name = "main/dispense_overview.html"
    history_limit = 10
    form_class = DispenseStartForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = Location.objects.get(
            id=self.request.session["location_id"]
        )
        context["dispensed"] = Dispensed.objects.filter(location=context["location"])[
            : self.history_limit
        ]
        return context

    def get(self, request, *args, **kwargs):
        if "location_id" not in self.request.session:
            return redirect(reverse("main:logout"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        self.id_card_no = form.cleaned_data["id_card_no"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse("main:dispense_new", kwargs={"id_card_no": self.id_card_no})


class DispenseNewView(LoginRequiredMixin, TemplateView):
    template_name = "main/dispense_new.html"

    def get_materials(self):
        return Material.get_available(self.request.session["location_id"])

    def get_context_data(self, id_card_no, **kwargs):
        context = super().get_context_data(**kwargs)
        context["location"] = Location.objects.get(
            id=self.request.session["location_id"]
        )
        context["id_card_no"] = id_card_no
        context["forms"] = [DispenseItemForm(mat) for mat in self.get_materials()]
        return context

    def post(self, request, id_card_no, *args, **kwargs):
        for material in self.get_materials():
            form = DispenseItemForm(material, request.POST)
            if form.is_valid() and form.cleaned_data["quantity"] > 0:
                Dispensed.objects.create(
                    material=material,
                    user=request.user,
                    location_id=request.session["location_id"],
                    quantity=form.cleaned_data["quantity"],
                    id_card_no=id_card_no,
                )
        return redirect(reverse("main:dispense"))


class DispenseEditView(LoginRequiredMixin, UpdateView):
    template_name = "main/dispense_edit.html"
    model = Dispensed
    fields = ["id_card_no", "quantity"]

    def get_success_url(self):
        return reverse("main:dispense")


class RegionListView(ListView):
    template_name = "main/region-list.html"
    model = Region

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(status=Region.ACTIVE)


class RegionView(DetailView):
    template_name = "main/region.html"
    model = Region
    slug_field = "id"
    slug_url_kwarg = "id"


class LocationView(DetailView):
    template_name = "main/location.html"
    model = Location
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["volunteers_count"] = self.object.staff.filter(
            locationstaff__status=LocationStaff.VOLUNTEER
        ).count()
        context["admins_count"] = self.object.staff.filter(
            locationstaff__status=LocationStaff.ADMIN
        ).count()
        context["pending_count"] = self.object.staff.filter(
            locationstaff__status=LocationStaff.PENDING
        ).count()
        return context

main/templates/main/about.html
{% extends "main/base.html" %}
{% block title %}O aplikaci{% endblock title %}
{% block content %}

<p>Intenzivně pracujeme na první verzi aplikace. Již brzy!</p>

{% endblock content %}

main/templates/main/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="cs">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Otevřená města z.s.">

    <!--[if lt IE 9]>
      <script src="{% static "js/html5shiv.min.js" %}"></script>
    <![endif]-->

    <link rel="icon" href="{% static "images/favicon.ico" %}">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/fontawesome.all.min.css" %}" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    {% block css %}{% endblock %}

    <title>{% block title %}{% endblock title %} - Výdej materiálu</title>
  </head>
  <body class="d-flex flex-column vh-100">
    <nav class="navbar navbar-expand-sm navbar-dark flex-shrink-0">
      <div class="container">
        <a class="navbar-brand" href="/">
          <i class="fas fa-plus-square mr-2"></i>
          Výdej materiálu
        </a>

        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target=".navbar-collapse"
                aria-controls=".navbar-collapse">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            {% include "main/menu_item_snippet.html" with view_name="main:region_list" title="Oblasti" %}
            {% include "main/menu_item_snippet.html" with view_name="main:about" title="O&nbsp;aplikaci" %}
          </ul>
          <ul class="navbar-nav ml-auto">
            {% include "main/menu_item_snippet.html" with view_name="main:dispense" title="Výdej" %}
            {% include "main/menu_item_snippet.html" with view_name="admin:index" title="Spravovat" %}
            {% if request.user.is_authenticated %}
              {% include "main/menu_item_snippet.html" with view_name="main:logout" title="Odhlásit" %}
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <main role="main" class="flex-grow-1">
      <div class="container">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} mt-3">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
        {% endfor %}
        {% endif %}

        <div class="my-4">
          {% block content %}
          {% endblock content %}
        </div>
      </div>
    </main>

    <footer class="footer w-100 mt-auto py-2 mt-3 border-top flex-shrink-0 bg-dark text-light">
      <div class="container text-center">
        <div>
          <a href="https://otevrenamesta.cz/">
            <img src="{% static "images/logo-om.png" %}" height="20">
          </a>
        </div>
      </div>
    </footer>

    <script src="{% static "js/jquery-3.3.1.slim.min.js" %}"></script>
    <script src="{% static "js/popper.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    {% block javascript %}{% endblock javascript %}
  </body>
</html>

main/templates/main/dispense_blocked.html
{% extends "main/base.html" %}
{% block title %}Výdej{% endblock title %}
{% block content %}

<div class="text-center mt-5">
  <div class="h3">
    <i class="fa fa-ban" aria-hidden="true"></i>
  </div>
  <h2 class="h5 mt-2">Je nám to líto</h2>
  <p>Kordinátor odmítl vaši účast na výdeji v této lokalitě.</p>
</div>

{% endblock content %}

main/templates/main/dispense_edit.html
{% extends "main/base.html" %}
{% block title %}Výdej{% endblock title %}
{% block content %}

<h2 class="h5 mt-4 mb-2">Úprava záznamu</h2>

<form method="post" action="{% url "main:dispense_edit" pk=object.pk %}" autocomplete="off">
  {% csrf_token %}

  <table class="table table-sm">

    <tr>
      <td class="align-middle">
        {{ form.id_card_no.label_tag }}
      </td>
      <td colspan="3">
        <input class="form-control text-monospace"
               type="number" min="0" max="999999999" step="1"
               id="form.id_card_no.id_for_label" name="{{ form.id_card_no.html_name }}"
               value="{{ form.id_card_no.value }}"
               tabindex="1">
      </td>
    </tr>

    {% include 'main/dispense_form_snippet.html' with material=object.material quantity_field=form.quantity %}

    <tr>
      <td colspan="2"></td>
      <td>
        <button type="submit"
                class="btn btn-primary mt-2"
                style="width: 100%"
                tabindex="2">Uložit</button>
      </td>
      <td></td>
    </tr>

  </table>
</form>

{% include "main/dispense_location_snippet.html" with location=object.location %}

{% endblock content %}

main/templates/main/dispense_form_snippet.html
<tr>
  <td class="align-middle">{{ material.name }}</td>
  <td style="width: 0">
    <button class="btn btn-danger"
            tabindex="-1"
            data-decrement="#{{ quantity_field.id_for_label }}">
      <i class="fa fa-minus"></i>
    </button>
  </td>
  <td style="width: 40px">
    <input class="form-control"
           type="number" min="0" step="1" value="{{ quantity_field.value }}"
           style="width: 5em"
           id="{{ quantity_field.id_for_label }}" name="{{ quantity_field.html_name }}"
           data-limit="3"
           tabindex="1">
  </td>
  <td style="width: 0">
    <button class="btn btn-success"
            tabindex="-1"
            data-increment="#{{ quantity_field.id_for_label }}">
      <i class="fa fa-plus"></i>
    </button>
  </td>
</tr>

main/templates/main/dispense_location_snippet.html
<hr>
<p>
  Vydáváte v lokalitě
  <a href="{% url "main:location" location.id %}"><small class="text-muted">#</small>{{ location.id }} {{ location.name }}</a>
  (oblast <a href="{% url "main:region" location.region_id %}">{{ location.region_name }}</a>)
</p>

main/templates/main/dispense_overview.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Výdej{% endblock title %}
{% block content %}

<h2 class="h5 mt-4">Ověření dokladu</h2>

{% crispy form %}

<h2 class="h5">Historie</h2>

<table class="table table-sm">

  <tr>
    <th>datum</th>
    <th>číslo dokladu</th>
    <th>materiál</th>
    <th>množství</th>
    <th></th>
  </tr>

  {% for disp in dispensed %}
  <tr>
    <td class="align-middle">{{ disp.created }}</td>
    <td class="align-middle">{{ disp.id_card_no }}</td>
    <td class="align-middle">{{ disp.material.name }}</td>
    <td class="align-middle">{{ disp.quantity }}</td>
    <td style="width: 0">
      <a href="{% url 'main:dispense_edit' pk=disp.pk %}" class="btn btn-sm btn-primary" tabindex="3">
        <i class="fa fa-edit" aria-hidden="true"></i>
      </a>
    </td>
  </tr>
  {% endfor %}

</table>

{% include "main/dispense_location_snippet.html" %}

{% endblock content %}

main/templates/main/dispense_pending.html
{% extends "main/base.html" %}
{% block title %}Výdej{% endblock title %}
{% block content %}

<div class="text-center mt-5">
  <div class="spinner-border" aria-hidden="true"></div>
  <h2 class="h5 mt-2">Vyčkejte na potvrzení</h2>
  <p>Zahájení výdeje materiálu musí nejprve potvrdit koordinátor lokality.</p>
</div>

{% endblock content %}

main/templates/main/home.html
{% extends "main/base.html" %}
{% block title %}Home{% endblock title %}
{% block content %}

<p>Intenzivně pracujeme na první verzi aplikace. Již brzy!</p>

{% endblock content %}

main/templates/main/location.html
{% extends "main/base.html" %}
{% load markdownify %}

{% block title %}{{object.name}}{% endblock title %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url "main:region_list" %}">Oblasti</a>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url "main:region" object.region.id %}">{{object.region.name}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
      {{object.name}}
    </li>
  </ol>
</nav>

<h5>Výdejní lokalita <small class="text-muted">#</small>{{object.id}}</h5>
<table class="table table-sm table-bordered">
  <tr>
    <th style="width: 10em">Název lokality</th>
    <td>{{object.name}}</td>
  </tr>

  <tr>
    <th>Telefonní číslo</th>
    {% if object.phone %}
    <td>{{object.phone}}</td>
    {% else %}
    <td><i>není uvedeno</i></td>
    {% endif %}
  </tr>

  <tr>
    <th>Adresa</th>
    {% if object.address %}
    <td>{{ object.address|linebreaksbr }}</td>
    {% else %}
    <td><i>není uvedena</i></td>
    {% endif %}
  </tr>

  <tr>
    <th>Personál</th>
    <td>
      {% if admins_count == 1 %}
        {{ admins_count }} koordinátor
      {% elif admins_count <= 4 and admins_count > 1 %}
        {{ admins_count }} koordinátoři
      {% else %}
        {{ admins_count }} koordinátorů
      {% endif %}
      <br>

      {% if volunteers_count == 1 %}
        {{ volunteers_count }} dobrovolník
      {% elif volunteers_count <= 4 and volunteers_count > 1 %}
        {{ volunteers_count }} dobrovolníci
      {% else %}
        {{ volunteers_count }} dobrovolníků
      {% endif %}
      <br>

      {% if pending_count == 1 %}
        {{ pending_count }} čekatel
      {% elif pending_count <= 4 and pending_count > 1 %}
        {{ pending_count }} čekatelé
      {% else %}
        {{ pending_count }} čekatelů
      {% endif %}
      <br>

      <a href="{% url "main:login" %}?location={{ object.id }}">chci pomoci s výdejem</a>
    </td>
  </tr>
</table>

<h5>Popis</h5>
<div class="description">
  {% if object.about %}
    {{ object.about|markdownify }}
  {% else %}
    <i>není uveden</i>
  {% endif %}
</div>

{% endblock content %}

main/templates/main/menu_item_snippet.html
<li class="nav-item {% if request.resolver_match.view_name == view_name %}active{% endif %}">
  <a class="nav-link" href="{% url view_name %}">{{ title }}</a>
</li>

main/templates/main/region.html
{% extends "main/base.html" %}
{% load markdownify %}

{% block title %}{{object.name}}{% endblock title %}

{% block content %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">
      <a href="{% url "main:region_list" %}">Oblasti</a>
    </li>
    <li class="breadcrumb-item active">
      {{object.name}}
    </li>
  </ol>
</nav>

<h4>{{ object.name }}</h4>

{{ object.about|markdownify }}

<h5 class="mt-4">Lokality</h5>
<p>
  Výdej materiálu probíhá v&nbsp;níže uvedených lokalitách:
</p>

<table class="table table-sm">
  {% for location in object.location_set.all %}
  <tr>
    <td style="width: 0"><small class="text-muted">#</small>{{location.id}}</td>
    <th>
      <a href="{% url "main:location" location.id %}">
        {{location.name}}
      </a>
    </th>
    <!-- TODO: Add number of volunteers and pending here. -->
  </tr>
  {% endfor %}
</table>

{% endblock content %}

main/templates/main/region_list.html
{% extends "main/base.html" %}

{% block title %}Oblasti{% endblock title %}

{% block content %}

<h2 class="h3">Výdej materiálu</h2>

<p>
  Tato aplikace slouží pro zajištění výdeje materiálu v&nbsp;čase COVID-19
  krize. Pokud nám chcete s&nbsp;výdejem pomoci, najděte si svou oblast
  v&nbsp;seznamu níže a pokračujte vyhledáním vám blízké lokality, kde ještě
  není dobrovolníků dostatek.
</p>

<h3 class="h4 mt-4">Oblasti</h3>
<p>Výdej materiálu probíhá v&nbsp;níže uvedených oblastech:</p>

<table class="table table-sm">
  {% for region in object_list %}
  <tr>
    <th>
      <a href="{% url "main:region" region.id %}">
        {{region.name}}
      </a>
    </th>
    <td>
      {% with cnt=region.location_set.count %}
      {% if cnt == 1 %}
      {{cnt}} lokalita
      {% elif cnt > 1 and cnt <= 4 %}
      {{cnt}} lokality
      {% else %}
      {{cnt}} lokalit
      {% endif %}
      {% endwith %}
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock content %}

main/templates/main/under_construction.html
{% extends "main/base.html" %}
{% block title %}Připravujeme{% endblock title %}
{% block content %}

<p>Stránka zatím chybí. Intenzivně na tom pracujeme!</p>

{% endblock content %}